version: '2.1'

networks:
  smmp_net:
    name: smmp_net
    driver: bridge
    ipam:
      driver: default

services:

  redis_db:
    image: "redis:latest"
    container_name: smmp-rediscache
    ports:
      - "6379:6379"
    networks:
      smmp_net:
        aliases:
          - redis_host

  smmp_api:
    build: .
    container_name: smmp-api
    environment:
      - PORT=${PORT}
      - HOST=${HOST}
      - STAGE=${STAGE}
      - PINATA_API_KEY=${PINATA_API_KEY}
      - PINATA_SECRET_API_KEY=${PINATA_SECRET_API_KEY}
      - REDIS_HOST=redis_host
      - REDIS_PORT=6379
      - REDIS_TTL=240000000
    ports:
      - "3000:3000"
    networks:
      smmp_net:
        aliases:
          - api_host