name: Deploy DEV

env: 
  STAGE: dev
  CONTAINER_NAME: smmp-api
  DOCKER_IMAGE: rogrp6/smmp-api
  DOCKER_IMAGE_TAG: dev
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  SERVER_HOST: ${{ secrets.DEV_SSH_HOST }}
  SERVER_USER: ${{ secrets.DEV_SSH_USER }}
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  PINATA_API_KEY: ${{ secrets.DEV_PINATA_API_KEY }}
  PINATA_SECRET_API_KEY: ${{ secrets.DEV_PINATA_SECRET_API_KEY }}

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build the Docker image
      run: docker build . -t $DOCKER_IMAGE:$DOCKER_IMAGE_TAG
      
    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ env.DOCKER_PASSWORD }}
        
    - name: Push the Docker image
      run: docker push $DOCKER_IMAGE:$DOCKER_IMAGE_TAG
      
    - name: Server pull and run Docker image 
      uses: appleboy/ssh-action@master
      with:
        key : ${{ env.SSH_PRIVATE_KEY }}
        host: ${{ env.SERVER_HOST }}
        username: ${{ env.SERVER_USER }}
        script: |
          sudo docker stop ${{ env.CONTAINER_NAME }} ; \
          sudo docker run --pull always --rm --name ${{ env.CONTAINER_NAME }} -d -p 80:3000 \
          -e PORT=3000 \
          -e HOST=0.0.0.0 \
          -e STAGE=${{ env.STAGE }} \
          -e PINATA_API_KEY=${{ env.PINATA_API_KEY }} \
          -e PINATA_SECRET_API_KEY=${{ env.PINATA_SECRET_API_KEY }} \
          $DOCKER_IMAGE:${{ env.DOCKER_IMAGE_TAG }}

