name: Deploy DEV

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build the Docker image
      run: docker build . -t rogrp6/smmp-api:dev
      
    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Push the Docker image
      run: docker push rogrp6/smmp-api:dev
      
    - name: Server pull and run Docker image 
      uses: appleboy/ssh-action@master
      with:
        key : ${{ secrets.SSH_PRIVATE_KEY }}
        host: ${{ secrets.REMOTE_HOST_DEV }}
        username: ${{ secrets.REMOTE_USER }}
        script: sudo docker pull rogrp6/smmp-api:dev ; sudo docker stop smmp-api ; sudo docker rm smmp-api ; sudo docker run --name smmp-api -d -p 80:3000 -e PORT=3000 -e HOST=0.0.0.0 rogrp6/smmp-api:dev

