name: Deploy via SSH

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
          
    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        key : ${{ secrets.SSH_PRIVATE_KEY }}
        host: ${{ secrets.REMOTE_HOST_PROD }}
        username: ${{ secrets.REMOTE_USER }}
        script: sudo docker pull rogrp6/smmp-api:latest && sudo docker stop smmp-api || sudo docker run --name smmp-api -d -p 80:3000 -e PORT=3000 -e HOST=0.0.0.0 rogrp6/smmp-api:latest

